### PR TITLE
Revert "Change a bit app.js"

### PR DESCRIPTION
**Pull request by Shubhamrawat5**
Reverts Shubhamrawat5/apple-playlist-downloader#8

### CODE REVIEW

**Comment by Shubhamrawat5** [comment]
Now i checked and that <= was also wrong as if when only 1 result is found then also array length is 1 so now new condition can be..

// when no result then [{}] is returned so length is always 1, when 1 result then [{id:"",etc:""}]
  if (!data["audios"][""][0].id)

**Comment by antoinebollengier** [comment]
I've got this error
TypeError: Cannot read properties of undefined (reading '0')

**Comment by antoinebollengier** [comment]
{ audios: { error: [ {} ] } }
==[ SONG NOT FOUND! ]== : Hello My Love
{ audios: { error: [ {} ] } }
==[ SONG NOT FOUND! ]== : Little Bit of Love
{ audios: { error: [ {} ] } }
==[ SONG NOT FOUND! ]== : Graveyard
{ audios: { error: [ {} ] } }
==[ SONG NOT FOUND! ]== : Lease On Life

**Comment by antoinebollengier** [comment]
Maybe website owners have modified something because the code can't download any song.

**Comment by antoinebollengier** [comment]
Capture d’écran 2021-10-04 à 13 28 32

**Comment by Shubhamrawat5** [comment]
It's working fine for me, can you re-clone and then try from starting.

**Comment by Shubhamrawat5** [comment]
ari

**Comment by antoinebollengier** [comment]
Ok, I understand, this is my IP address. I tried with a vpn and it works fine.

**Pull request merged**
