### PR TITLE
Adding ID3 tags to mp3 file

### PR DESCRIPTION
**Pull request by Domique**
Hi, I've just added a ID3 compatibility ->
The code search using node-itunes-search all the tags from the tracks and write them with node-id3 to the mp3 file.
Writes :
- Cover image
- Artist, Album, Year, Genre, Track number

### CODE REVIEW

**Comment by Shubhamrawat5** [comment]
Great work !

**Comment by Domique** [comment]
Now it's look like this : 
Capture d’écran 2021-09-26 à 18 32 25
Capture d’écran 2021-09-26 à 18 32 17

**Comment by Domique** [comment]
I will post a commit too for your web app project

**Comment by Shubhamrawat5** [comment]
Yeah. I've checked and it's really great with cover images and all, but I've noticed that you've removed some of the comments, so can you write all those comments back and also update the package.json file with the packages you used additionally.

**Comment by Domique** [comment]
I think it's done

**Pull request merged**
