### PR TITLE
Adds support for albums, simple CLI, refactors the app.js into several files

### PR DESCRIPTION
**Pull request by fuzzywalrus**
This leaves a bunch of the original code in spirit but should be a quality of life update. The Readme has an overview of the changes. Each of the major functions is now in it's own JS file making it a bit easier to manage. 

The functionality largely remains unchanged.

### CODE REVIEW

**Comment by b5i** [comment]
> This leaves a bunch of the original code in spirit but should be a quality of life update. The Readme has an overview of the changes. Each of the major functions is now in it's own JS file making it a bit easier to manage. 
> 
> 
> 
> The functionality largely remains unchanged.

Will you also post your update to the npm repo or I'll do the work for it?

**Comment by Shubhamrawat5** [comment]
Okay, nice work. Will check

**Comment by fuzzywalrus** [comment]
@b5i  I saw your lib and tried it but it didn't work when I pulled it but looking at it, it just uses the older request. Since you had the outstanding PR I wasn't sure if it'd make it in or not. I'm happy to use your method of the terminal input as a lot more robust and it already has a NPM. 

@Shubhamrawat5 Feel free to modify heavily as you see fit. I left the function names intact and such.

**Comment by b5i** [comment]
> @b5i  I saw your lib and tried it but it didn't work when I pulled it but looking at it, it just uses the older request. Since you had the outstanding PR I wasn't sure if it'd make it in or not. I'm happy to use your method of the terminal input as a lot more robust and it already has a NPM. 
Ok yes, I didn't have time to adapt to the changes made but I'll do ASAP (probably in a few days and I'll update the NPM package).

**Comment by Shubhamrawat5** [comment]
Will check it soon and sorry for the delay

**Comment by Justman10000** [comment]
@Shubhamrawat5

I see in the code that you are using [Slider](https://slider.kz)! Problem? Not a single tag!

**Comment by Shubhamrawat5** [comment]
Yes, I'm using slider to download songs and currently It's working fine

**Comment by Justman10000** [comment]
> Yes, I'm using slider to download songs and currently It's working fine

Like i said:

> Not a single tag!
grafik

**Comment by Justman10000** [comment]
> Ohh, I'm not sure of the meta tags of a song file, currently in the code those meta tags are added by some other developer.
> 
> I've no problem with giving credits/tags

But it is really shit to have to add them manually all the time! You can't see data like the publication date (DD.MM..YYYY) anywhere either

**Comment by Shubhamrawat5** [comment]
@fuzzywalrus  Hi, I was working on other stuff but now I'll work on this in upcoming days, will improve it.

There are many conflicts with this PR and also many commits, I think It won't be possible to merge it now, Also I found one API which can give playlist info, Also there are some changes in code.

I'm closing this PR now.

If you still want to contribute, I'm happy to work with you

**Pull request closed without merging**
